function ssxy_te_gradx = spgr_2comp_exchg0_mag1_freq0_gradx(M0,ff,T1f,T1s,T2f,T2s,kap,flip,TR,TE,R2pf,R2ps)
%SPGR_2COMP_EXCHG0_MAG1_FREQ0_GRADX
%    SSXY_TE_GRADX = SPGR_2COMP_EXCHG0_MAG1_FREQ0_GRADX(M0,FF,T1F,T1S,T2F,T2S,KAP,FLIP,TR,TE,R2PF,R2PS)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    21-Jan-2018 18:21:50

t2 = flip.*kap;
t3 = 1.0./T1f;
t4 = TR.*t3;
t5 = exp(t4);
t6 = sin(t2);
t7 = cos(t2);
t8 = 1.0./T1s;
t9 = TR.*t8;
t10 = exp(t9);
t11 = 1.0./T2f;
t12 = R2pf+t11;
t25 = TE.*t12;
t13 = exp(-t25);
t14 = t5-t7;
t15 = 1.0./t14;
t16 = exp(-t4);
t17 = t16-1.0;
t18 = 1.0./T2s;
t19 = R2ps+t18;
t27 = TE.*t19;
t20 = exp(-t27);
t21 = t7-t10;
t22 = 1.0./t21;
t23 = exp(-t9);
t24 = t23-1.0;
t26 = 1.0./T1f.^2;
t28 = ff-1.0;
t29 = 1.0./T1s.^2;
ssxy_te_gradx = [-ff.*t5.*t6.*t13.*t15.*t17-t6.*t10.*t20.*t22.*t24.*t28,-M0.*t5.*t6.*t13.*t15.*t17-M0.*t6.*t10.*t20.*t22.*t24,-M0.*TR.*ff.*t6.*t13.*t15.*t26+M0.*TR.*ff.*t5.*t6.*t13.*t15.*t17.*t26-M0.*TR.*ff.*t6.*t13.*1.0./t14.^2.*t17.*t26.*exp(TR.*t3.*2.0),-M0.*TR.*t6.*t20.*t22.*t28.*t29+M0.*TR.*t6.*t10.*t20.*t22.*t24.*t28.*t29+M0.*TR.*t6.*t20.*1.0./t21.^2.*t24.*t28.*t29.*exp(TR.*t8.*2.0),-M0.*1.0./T2f.^2.*TE.*ff.*t5.*t6.*t13.*t15.*t17,-M0.*1.0./T2s.^2.*TE.*t6.*t10.*t20.*t22.*t24.*t28];
