function smxy_tem = dess_2comp_echo2_exchg0_mag1_freq0(M0,ff,T1f,T1s,T2f,T2s,kap,flip,TR,TEm,R2pf,R2ps)
%DESS_2COMP_ECHO2_EXCHG0_MAG1_FREQ0
%    SMXY_TEM = DESS_2COMP_ECHO2_EXCHG0_MAG1_FREQ0(M0,FF,T1F,T1S,T2F,T2S,KAP,FLIP,TR,TEM,R2PF,R2PS)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    21-Jan-2018 17:18:47

t2 = 1.0./T2f;
t3 = exp(TR.*t2.*-2.0);
t5 = 1.0./T1f;
t6 = TR.*t5;
t7 = exp(-t6);
t8 = flip.*kap;
t9 = cos(t8);
t4 = -t7+t9;
t10 = 1.0./T2s;
t11 = exp(TR.*t10.*-2.0);
t13 = 1.0./T1s;
t14 = TR.*t13;
t15 = exp(-t14);
t12 = t9-t15;
t16 = flip.*kap.*(1.0./2.0);
t17 = tan(t16);
smxy_tem = -M0.*t17.*exp(-TEm.*(R2ps-t10)).*abs(sqrt((t11-1.0)./(t11.*t12.^2.*1.0./(t9.*t15-1.0).^2-1.0))-1.0).*(ff-1.0)+M0.*ff.*t17.*exp(-TEm.*(R2pf-t2)).*abs(sqrt((t3-1.0)./(t3.*t4.^2.*1.0./(t7.*t9-1.0).^2-1.0))-1.0);
