function spxy_tep = dess_2comp_echo1_exchg0_mag0_freq0(M0,ff,T1f,T1s,T2f,T2s,kap,Dwf,Dws,flip,TR,TEp,R2pf,R2ps)
%DESS_2COMP_ECHO1_EXCHG0_MAG0_FREQ0
%    SPXY_TEP = DESS_2COMP_ECHO1_EXCHG0_MAG0_FREQ0(M0,FF,T1F,T1S,T2F,T2S,KAP,DWF,DWS,FLIP,TR,TEP,R2PF,R2PS)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    22-Jan-2018 14:23:56

t2 = 1.0./T1s;
t8 = TR.*t2;
t3 = exp(-t8);
t4 = flip.*kap;
t5 = cos(t4);
t6 = 1.0./T2s;
t7 = exp(TR.*t6.*-2.0);
t9 = -t3+t5;
t10 = t3.*t5;
t11 = t10-1.0;
t12 = flip.*kap.*(1.0./2.0);
t13 = tan(t12);
t14 = 1.0./T1f;
t18 = TR.*t14;
t15 = exp(-t18);
t16 = 1.0./T2f;
t17 = exp(TR.*t16.*-2.0);
t19 = t5-t15;
t20 = t5.*t15;
t21 = t20-1.0;
spxy_tep = M0.*t13.*exp(-TEp.*(R2ps+t6)).*exp(Dws.*TEp.*1i).*(ff-1.0).*((t9.*sqrt((t7-1.0)./(t7.*t9.^2.*1.0./t11.^2-1.0)))./t11-1.0).*1i-M0.*ff.*t13.*exp(-TEp.*(R2pf+t16)).*exp(Dwf.*TEp.*1i).*((t19.*sqrt((t17-1.0)./(t17.*t19.^2.*1.0./t21.^2-1.0)))./t21-1.0).*1i;
