function smxy_tem = dess_2comp_echo2_exchg0_mag0_freq0(M0,ff,T1f,T1s,T2f,T2s,kap,Dwf,Dws,flip,TR,TEm,R2pf,R2ps)
%DESS_2COMP_ECHO2_EXCHG0_MAG0_FREQ0
%    SMXY_TEM = DESS_2COMP_ECHO2_EXCHG0_MAG0_FREQ0(M0,FF,T1F,T1S,T2F,T2S,KAP,DWF,DWS,FLIP,TR,TEM,R2PF,R2PS)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    22-Jan-2018 14:23:57

t2 = 1.0./T2f;
t3 = exp(TR.*t2.*-2.0);
t5 = 1.0./T1f;
t6 = TR.*t5;
t7 = exp(-t6);
t8 = flip.*kap;
t9 = cos(t8);
t4 = -t7+t9;
t10 = flip.*kap.*(1.0./2.0);
t11 = tan(t10);
t12 = 1.0./T2s;
t13 = exp(TR.*t12.*-2.0);
t15 = 1.0./T1s;
t16 = TR.*t15;
t17 = exp(-t16);
t14 = t9-t17;
smxy_tem = M0.*t11.*exp(Dws.*TEm.*-1i).*exp(-TEm.*(R2ps-t12)).*(sqrt((t13-1.0)./(t13.*t14.^2.*1.0./(t9.*t17-1.0).^2-1.0))-1.0).*(ff-1.0).*-1i+M0.*ff.*t11.*exp(Dwf.*TEm.*-1i).*exp(-TEm.*(R2pf-t2)).*(sqrt((t3-1.0)./(t3.*t4.^2.*1.0./(t7.*t9-1.0).^2-1.0))-1.0).*1i;
