function spxy_tep = dess_2comp_echo1_exchg0_mag1_freq0(M0,ff,T1f,T1s,T2f,T2s,kap,flip,TR,TEp,R2pf,R2ps)
%DESS_2COMP_ECHO1_EXCHG0_MAG1_FREQ0
%    SPXY_TEP = DESS_2COMP_ECHO1_EXCHG0_MAG1_FREQ0(M0,FF,T1F,T1S,T2F,T2S,KAP,FLIP,TR,TEP,R2PF,R2PS)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    21-Jan-2018 17:18:47

t2 = 1.0./T1s;
t8 = TR.*t2;
t3 = exp(-t8);
t4 = flip.*kap;
t5 = cos(t4);
t6 = 1.0./T2s;
t7 = exp(TR.*t6.*-2.0);
t9 = -t3+t5;
t10 = t3.*t5;
t11 = t10-1.0;
t12 = 1.0./T1f;
t16 = TR.*t12;
t13 = exp(-t16);
t14 = 1.0./T2f;
t15 = exp(TR.*t14.*-2.0);
t17 = t5-t13;
t18 = t5.*t13;
t19 = t18-1.0;
t20 = flip.*kap.*(1.0./2.0);
t21 = tan(t20);
spxy_tep = -M0.*t21.*abs(-(t9.*sqrt((t7-1.0)./(t7.*t9.^2.*1.0./t11.^2-1.0)))./t11+1.0).*exp(-TEp.*(R2ps+t6)).*(ff-1.0)+M0.*ff.*t21.*abs(-(t17.*sqrt((t15-1.0)./(t15.*t17.^2.*1.0./t19.^2-1.0)))./t19+1.0).*exp(-TEp.*(R2pf+t14));
